pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
        maven {
            name = 'NeoForged'
            url = 'https://maven.neoforged.net/releases'
        }
    }
}

// This should match the folder name of the project, or else IDEA may complain
rootProject.name = 'bettermobcombat'
